"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2!sx2qt-hfr4_(f!ki#)i&mqni6-t00dmmcmyj@mr5_h8(76up"

# SECURITY WARNING: don't run with debug turned on in production!
# True开发 False生产
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['127.0.0.1', '47.105.91.154']

from dotenv import load_dotenv

load_dotenv()

import mimetypes

mimetypes.add_type("application/javascript", ".mjs", True)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "web",
    "corsheaders",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
#设置static和media静态文件路径
STATIC_URL='static/'
#STATIC_ROOT=BASE_DIR/'statiC'#生产阶段使用
# STATICFILES_DIRS=[
#     BASE_DIR /'static',
# ]

if not DEBUG:
    STATIC_ROOT = BASE_DIR / 'static'  # 生产阶段使用
else:
    STATICFILES_DIRS = [  # 开发阶段使用，生产阶段需要注释掉
        BASE_DIR / 'static',
    ]


# MEDIA_URL='http://127.0.0.1:8000/media/'
if DEBUG:
    MEDIA_URL = 'http://127.0.0.1:8000/media/'
else:
    MEDIA_URL = 'http://47.105.91.154/media/'

MEDIA_ROOT = BASE_DIR / 'media'


from datetime import timedelta
#使用JwT认证
REST_FRAMEWORK={
    'DEFAULT_AUTHENTICATION_CLASSES':(
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

#SIMPLE_JWT
SIMPLE_JWT ={
    'ACCESS_TOKEN_LIFETIME':timedelta(hours=2), #身份凭证
    'REFRESH_TOKEN_LIFETIME':timedelta(days=7),  #刷新身份凭证

    'ROTATE_REFRESH_TOKENS':True,
    'BLACKLIST_AFTER_ROTATION': True,

    'AUTH_HEADER_TYPES':('Bearer',),

    # 为了纯ip访问 额外的配置
    # 'AUTH_COOKIE_SECURE': False,   # 允许在 HTTP 环境下传输 Cookie (关键！)
    # 'AUTH_COOKIE_SAMESITE': 'Lax', # 不要用 None，在 HTTP 下 None 会被浏览器直接拦截
}

#跨域
CORS_ALLOW_CREDENTIALS= True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://47.105.91.154",
]

ASGI_APPLICATION = 'backend.asgi.application'

# 生产环境
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }
# 单机测试开发环境
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}
# 添加默认主键类型
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'