# Generated by Django 6.0.2 on 2026-02-10 15:12

import datetime
import django.db.models.deletion
import web.models.character
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "photo",
                    models.ImageField(upload_to=web.models.character.photo_upload_to),
                ),
                (
                    "background_image",
                    models.ImageField(
                        upload_to=web.models.character.background_image_upload_to
                    ),
                ),
                ("profile", models.TextField(max_length=100000)),
                (
                    "create_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2026,
                            2,
                            10,
                            15,
                            12,
                            38,
                            451417,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2026,
                            2,
                            10,
                            15,
                            12,
                            38,
                            451417,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userprofile",
                    ),
                ),
            ],
        ),
    ]
