# Generated by Django 6.0.2 on 2026-02-12 10:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 12, 10, 42, 56, 644517, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 12, 10, 42, 56, 644517, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
