# Generated by Django 6.0.2 on 2026-02-20 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_conversation_alter_character_create_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 20, 20, 47, 17, 88088, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 20, 20, 47, 17, 89086, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 20, 20, 47, 17, 86755, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 20, 20, 47, 17, 86755, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 20, 20, 47, 17, 86755, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="update_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 20, 20, 47, 17, 86755, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="conversationmember",
            name="join_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 20, 20, 47, 17, 88088, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="friend",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 20, 20, 47, 17, 88088, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 20, 20, 47, 17, 89086, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
