# Generated by Django 5.2.12 on 2026-03-06 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_systemprompt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AIMessage",
            new_name="AIFriendMessage",
        ),
    ]
